### PR TITLE
Frontend edu suffix enforcement w/ regex

### LINKED ISSUE #11: Verify email ends in .edu

### PR DESCRIPTION
**Pull request by jonathan-herring**
Closes #11

### CODE REVIEW

**Review by awaang — CHANGES_REQUESTED** [review]
Delete optional comment

**Comment by YoungHypo** [comment]
👍

**Review by YoungHypo — APPROVED** [review]
👍

**Review by YoungHypo — APPROVED** [review]

**Comment by CollinQ** [comment]
LGTM

**Review by CollinQ — APPROVED** [review]
lgtm

**Pull request merged**
