### PR TITLE
Profile Page

### LINKED ISSUE #46: UI for main profile page
- [x] The profile page is accessible to the user via bottom navbar navigation
- [x] The profile page displays information about the user, including name, email, graduation year, etc.
- [x] There is a button that allows the user to access an interface to modify certain details listed about them

### PR DESCRIPTION
**Pull request by CollinQ**

### CODE REVIEW

**Review by aqiu04 — APPROVED** [review]
Tested, looks good

**Review by jonathan-herring — APPROVED** [review]
LGTM

**Review by YoungHypo — APPROVED** [review]
We should add major, graduation year and other info for sign-up page.

**Review by awaang — COMMENTED** [review]
LGTM

**Review by awaang — APPROVED** [review]

**Pull request merged**
